name: Gradle Build

on:
  workflow_dispatch

jobs:
  run_build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true
      - name: Actual build
        run: ./gradlew common:android:compileReleaseKotlin
