name: Profile Gradle Build

jobs:
  cache_build:
    name: Cache Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build auth with cache
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: common:android:compileReleaseKotlin
          gradle-version: wrapper