name: Profile Gradle Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  profile_build:
    name: Profile Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true

      - name: Install gradle-profiler
        uses: sdkman/sdkman-action@main
        id: sdkman
        with:
          candidate: gradleprofiler
          version: 0.20.0

      - name: Profile build
        run: bash ci/profiler/profile_build.sh

      - name: Print raw profile results
        run: cat profile-out/benchmark.csv

      - name: Upload profile results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark_result
          path: profile-out