name: Profile Gradle Build

on:
  workflow_dispatch:
    inputs:
      warm_ups_count:
        description: 'Number of warm-up builds before actual benchmarking'
        required: true
        default: '3'

      iterations_count:
        description: 'Number of iterations which will be shown in actual build report'
        required: true
        default: '5'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  profile_build:
    name: Profile Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true

      - name: Install gradle-profiler
        uses: sdkman/sdkman-action@main
        id: sdkman
        with:
          candidate: gradleprofiler
          version: 0.20.0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install Pillow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      - name: Profile build
        run: bash ci/profiler/profile_build.sh
        env:
          WARM_UPS_COUNT: ${{ github.event.inputs.warm_ups_count }}
          ITERATIONS_COUNT: ${{ github.event.inputs.iterations_count }}

#      - name: Print raw profile results
#        run: bash ci/profiler/profile_print.sh
#
#      - name: Export raw profile results
#        run: printenv SLACK_MESSAGE

      - name: Generate image
        run: python ci/profiler/csv_to_image.py

      - name: Upload profile results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark_result
          path: benchmark.jpeg